[package]
name = "memer"
version = "0.1.0"
edition = "2021"
description = "Discord meme bot."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/tedbyron/memer"
license = "MIT OR Apache-2.0"
keywords = ["discord", "bot"]

[features]
default = []

[dependencies]
poise = "0.2.0"
tracing = "0.1.34"
once_cell = { version = "1.10.0", features = ["parking_lot"] }
anyhow = "1.0.57"
dotenv = { version = "0.15.0", optional = true }
moka = { version = "0.8.2", features = ["dash", "future"] }
roux = "1.3.11"

[dependencies.tokio]
version = "1.18.0"
features = ["rt-multi-thread", "macros", "signal", "parking_lot"]

[dependencies.tracing-subscriber]
version = "0.3.11"
features = ["std", "env-filter", "fmt", "ansi", "smallvec", "parking_lot"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
